### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by auvilink** [facebookresearch/flashlight#12]
Hi, there, since I don't have a CUDA compatible machine, I built Arrayfire without CUDA backend,  just cpu backend.

I set backend to cpu in CMakeFile.txt as follows:
set(FLASHLIGHT_BACKEND "CPU" CACHE STRING "Backend with which to build Arrayfire ML")

When issuing "cmake .." I encountered many errors:

"

CMake Error in CMakeLists.txt:
  Target "Common" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/michael/fb/flashlight/CUDA_TOOLKIT_INCLUDE-NOTFOUND"

  which is prefixed in the source directory.

"

Any idea how I can get this fixed? 

Thank you.

**Comment by auvilink** [comment]
Never mind, I commented out the CUDA line in CMakeLists.txt and it compiles.

**Comment by auvilink** [comment]
I commented out the CUDA line in CMakeLists, now "cmake .." works fine but "make" gives out the error: 

"flashlight/flashlight/distributed/backend/cpu/DistributedBackend.cpp:18:30: fatal error: gloo/mpi/context.h: No such file or directory
compilation terminated.
CMakeFiles/flashlight.dir/build.make:566: recipe for target 'CMakeFiles/flashlight.dir/flashlight/distributed/backend/cpu/DistributedBackend.cpp.o' failed
"

**Comment by auvilink** [comment]
@jacobkahn again, I followed the build docs :
"cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU"
and got the following errors:

"[  7%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/WeightNorm.cpp.o
CMakeFiles/flashlight.dir/build.make:1166: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Transform.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Transform.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/michael/fb/flashlight/flashlight/nn/modules/WeightNorm.cpp:14:1: error: expected constructor, destructor, or type conversion before ‘namespace’
 namespace fl {
 ^
CMakeFiles/flashlight.dir/build.make:1214: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/WeightNorm.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/WeightNorm.cpp.o] Error 1
CMakeFiles/Makefile2:931: recipe for target 'CMakeFiles/flashlight.dir/all' failed
make[1]: *** [CMakeFiles/flashlight.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
"

CMake version: 3.5.1, OS: Ubuntu 16.04. make: GNU Make 4.1

Thanks.

**Comment by ybee05** [comment]
> @jacobkahn
> 
> **### My machine is not CUDA compatible, could this be the issue?**
> 
> I followed the build docs :
> "cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU"
> and got the following errors:
> 
> "CMake Error in CMakeLists.txt:
> Target "Common" INTERFACE_INCLUDE_DIRECTORIES property contains path:
> 
> ```
> "/home/michael/fb/flashlight/CUDA_TOOLKIT_INCLUDE-NOTFOUND"
> ```
> if I comment out the CUDA in common/CMakeLists.txt, then it won't complain above error but gave out following errors:
> 
> "[ 7%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/WeightNorm.cpp.o
> CMakeFiles/flashlight.dir/build.make:1166: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Transform.cpp.o' failed
> make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Transform.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> /home/michael/fb/flashlight/flashlight/nn/modules/WeightNorm.cpp:14:1: error: expected constructor, destructor, or type conversion before ‘namespace’
> namespace fl {
> ^
> CMakeFiles/flashlight.dir/build.make:1214: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/WeightNorm.cpp.o' failed
> make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/WeightNorm.cpp.o] Error 1
> CMakeFiles/Makefile2:931: recipe for target 'CMakeFiles/flashlight.dir/all' failed
> make[1]: *** [CMakeFiles/flashlight.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
> "
> 
> CMake version: 3.5.1, OS: Ubuntu 16.04. make: GNU Make 4.1,
> gcc: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
> 
> Thanks.

I meet the same compile error with the same environment

**Comment by auvilink** [comment]
The installation document says:

"Dependencies

flashlight can be built with either a CUDA, **CPU (coming soon)**, or OpenCL (coming soon) backend. Requirements vary depending on which backend is selected. All dependencies must be built/installed before building flashlight.



CPU Backend Dependencies

The CPU backend is not currently supported.

"

https://fl.readthedocs.io/en/latest/installation.html#build-requirements

**### So I guess we are out of luck for now?**

**Comment by jacobkahn** [comment]
Fixed in 30c19496772d897ad86af39e042fb532af034d09. Thanks.

**Comment by jacobkahn** [comment]
@auvilink — regarding the CPU backend, full support is coming very soon. You can attempt to build the backend now if you'd like ([Intel MKL}(https://software.intel.com/en-us/mkl) and [MKL-DNN](https://github.com/intel/mkl-dnn/) , but only certain operations are supported. I'll be adding more dependency details/build instructions very soon.

**Comment by auvilink** [comment]
@jacobkahn Thanks for the quick fix on finding "CUDA_TOOLKIT_INCLUDE" issue.

However, the other errors remain if I try to build with CPU backend. I did install Intel MKL and MKL-DNN as suggested.

**[  7%] Building CXX object CMakeFiles/flashlight.dir/flashlight/nn/modules/View.cpp.o
/home/michael/fb/flashlight/flashlight/nn/modules/Transform.cpp:12:1: error: expected constructor, destructor, or type conversion before ‘namespace’
 namespace fl {
 ^
CMakeFiles/flashlight.dir/build.make:1166: recipe for target 'CMakeFiles/flashlight.dir/flashlight/nn/modules/Transform.cpp.o' failed
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/Transform.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:931: recipe for target 'CMakeFiles/flashlight.dir/all' failed
make[1]: *** [CMakeFiles/flashlight.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
"**

Thanks.

**Comment by jacobkahn** [comment]
@auvilink — what OS/compiler are you building this on, so I can reproduce?

**Comment by jacobkahn** [comment]
@auvilink — I just tested with these conditions, and I can't seem to reproduce. What `cmake` command are you using?

**Comment by auvilink** [comment]
@jacobkahn 

cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU

**Comment by jacobkahn** [comment]
@auvilink — I'm having trouble reproducing on a fresh Ubuntu 16.04 machine with gcc 5.4.

Can you try adding `#include`s for `<functional>`, `<sstream>`, `<string>`, and `<arrayfire.h>` at the top of `flashlight/nn/modules/Transform.cpp` and flashlight/nn/modules/Transform.h` and see if that solves the issue?

**Comment by auvilink** [comment]
@jacobkahn I restarted with a new machine (same environment) 
Now it works!

Thanks.
